Add sanity check on expected environment variables

diff --git a/src/php.yml b/src/php.yml
--- a/src/php.yml
+++ b/src/php.yml
@@ -40,6 +40,24 @@ commands:
                 type: env_var_name
                 default: BLACKFIRE_CLIENT_TOKEN
         steps:
+            - run:
+                  command: |
+                      if [ -z "${<< parameters.server_id >>}" ]; then
+                          echo "Error: << parameters.server_id >> is empty. Please ensure the environment variable << parameters.server_id >> has been added."
+                          exit 1
+                      fi
+                      if [ -z "${<< parameters.server_token >>}" ]; then
+                          echo "Error: << parameters.server_token >> is empty. Please ensure the environment variable << parameters.server_token >> has been added."
+                          exit 1
+                      fi
+                      if [ -z "${<< parameters.client_id >>}" ]; then
+                          echo "Error: << parameters.client_id >> is empty. Please ensure the environment variable << parameters.client_id >> has been added."
+                          exit 1
+                      fi
+                      if [ -z "${<< parameters.client_token >>}" ]; then
+                          echo "Error: << parameters.client_token >> is empty. Please ensure the environment variable << parameters.client_token >> has been added."
+                          exit 1
+                      fi
             - blackfire-agent/setup:
                   server_id: ${<< parameters.server_id >>}
                   server_token: ${<< parameters.server_token >>}
